[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps = bblanchon/ArduinoJson@^7.0.0
build_flags =
  -I${PROJECT_DIR}/../common
  -D ARDUINO_USB_CDC_ON_BOOT=1
  ; PK296A1-SG36: 1.8° motor × 36:1 gear = 0.05°/pulse
  -D MOTOR_FULL_STEPS_PER_REV=7200
  -D MOTOR_MICROSTEPS=1
  -D MOTOR_DIRECTION_INVERT=0
  -D MOTOR_MAX_OUTPUT_SPEED_DEG_SEC=300
